In [4]:
#1. Load the cortex dataset located in the archive of the last course.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

data= pd.read_csv('Data_Cortex_Nuclear.csv')
data.head()

MouseID  DYRK1A_N   ITSN1_N    BDNF_N     NR1_N    NR2A_N    pAKT_N  \
0   309_1  0.503644  0.747193  0.430175  2.816329  5.990152  0.218830   
1   309_2  0.514617  0.689064  0.411770  2.789514  5.685038  0.211636   
2   309_3  0.509183  0.730247  0.418309  2.687201  5.622059  0.209011   
3   309_4  0.442107  0.617076  0.358626  2.466947  4.979503  0.222886   
4   309_5  0.434940  0.617430  0.358802  2.365785  4.718679  0.213106   

    pBRAF_N  pCAMKII_N   pCREB_N   ...     pCFOS_N     SYP_N  H3AcK18_N  \
0  0.177565   2.373744  0.232224   ...    0.108336  0.427099   0.114783   
1  0.172817   2.292150  0.226972   ...    0.104315  0.441581   0.111974   
2  0.175722   2.283337  0.230247   ...    0.106219  0.435777   0.111883   
3  0.176463   2.152301  0.207004   ...    0.111262  0.391691   0.130405   
4  0.173627   2.134014  0.192158   ...    0.110694  0.434154   0.118481   

     EGR1_N  H3MeK4_N    CaNA_N  Genotype  Treatment  Behavior   class  
0  0.131790  0.128186  1.675652   Control  Memantine       C/S  c-CS-m  
1  0.135103  0.131119  1.743610   Control  Memantine       C/S  c-CS-m  
2  0.133362  0.127431  1.926427   Control  Memantine       C/S  c-CS-m  
3  0.147444  0.146901  1.700563   Control  Memantine       C/S  c-CS-m  
4  0.140314  0.148380  1.839730   Control  Memantine       C/S  c-CS-m  

[5 rows x 82 columns]

In [3]:
#2. Fill missing entries (NaNs) in the numerical columns with 0.
new_data = data.drop(columns=['MouseID','Genotype','Treatment','Behavior','class'])
new_data = new_data.fillna(0)
new_data.head(10)

DYRK1A_N   ITSN1_N    BDNF_N     NR1_N    NR2A_N    pAKT_N   pBRAF_N  \
0  0.503644  0.747193  0.430175  2.816329  5.990152  0.218830  0.177565   
1  0.514617  0.689064  0.411770  2.789514  5.685038  0.211636  0.172817   
2  0.509183  0.730247  0.418309  2.687201  5.622059  0.209011  0.175722   
3  0.442107  0.617076  0.358626  2.466947  4.979503  0.222886  0.176463   
4  0.434940  0.617430  0.358802  2.365785  4.718679  0.213106  0.173627   
5  0.447506  0.628176  0.367388  2.385939  4.807635  0.218578  0.176233   
6  0.428033  0.573696  0.342709  2.334224  4.473130  0.225173  0.184004   
7  0.416923  0.564036  0.327703  2.260135  4.268735  0.214834  0.179668   
8  0.386311  0.538428  0.317720  2.125725  4.063950  0.207222  0.167778   
9  0.380827  0.499294  0.362462  2.096266  3.598587  0.227649  0.188093   

   pCAMKII_N   pCREB_N    pELK_N    ...        SHH_N     BAD_N  BCL2_N  \
0   2.373744  0.232224  1.750936    ...     0.188852  0.122652     0.0   
1   2.292150  0.226972  1.596377    ...     0.200404  0.116682     0.0   
2   2.283337  0.230247  1.561316    ...     0.193685  0.118508     0.0   
3   2.152301  0.207004  1.595086    ...     0.192112  0.132781     0.0   
4   2.134014  0.192158  1.504230    ...     0.205604  0.129954     0.0   
5   2.141282  0.195188  1.442398    ...     0.190469  0.131575     0.0   
6   2.012414  0.195789  1.612036    ...     0.181610  0.141806     0.0   
7   2.007985  0.189803  1.424601    ...     0.191561  0.141013     0.0   
8   1.861514  0.180684  1.261891    ...     0.186378  0.139589     0.0   
9   1.717861  0.188093  1.414329    ...     0.189523  0.183678     0.0   

      pS6_N   pCFOS_N     SYP_N  H3AcK18_N    EGR1_N  H3MeK4_N    CaNA_N  
0  0.106305  0.108336  0.427099   0.114783  0.131790  0.128186  1.675652  
1  0.106592  0.104315  0.441581   0.111974  0.135103  0.131119  1.743610  
2  0.108303  0.106219  0.435777   0.111883  0.133362  0.127431  1.926427  
3  0.103184  0.111262  0.391691   0.130405  0.147444  0.146901  1.700563  
4  0.104784  0.110694  0.434154   0.118481  0.140314  0.148380  1.839730  
5  0.106476  0.109446  0.439833   0.116657  0.140766  0.142180  1.816389  
6  0.097834  0.111483  0.406293   0.137229  0.156682  0.157499  1.528484  
7  0.099494  0.113080  0.382532   0.123376  0.155612  0.159409  1.652658  
8  0.105145  0.105490  0.435687   0.125173  0.152711  0.158235  1.834599  
9  0.093300  0.116906  0.414793   0.146133  0.188849  0.192334  1.516862  

[10 rows x 77 columns]

In [15]:
#3. Subtract the mean from each numerical column (standardize data).

In [17]:
new_data.describe()

DYRK1A_N      ITSN1_N       BDNF_N        NR1_N       NR2A_N  \
count  1080.000000  1080.000000  1080.000000  1080.000000  1080.000000   
mean      0.424627     0.615388     0.318202     2.290888     3.833256   
std       0.250022     0.253382     0.052098     0.367300     0.953532   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.287847     0.472764     0.287112     2.056486     3.149320   
50%       0.366125     0.565494     0.316462     2.295648     3.738908   
75%       0.487574     0.697500     0.348039     2.528035     4.425107   
max       2.516367     2.602662     0.497160     3.757641     8.482553   

            pAKT_N      pBRAF_N    pCAMKII_N      pCREB_N       pELK_N  \
count  1080.000000  1080.000000  1080.000000  1080.000000  1080.000000   
mean      0.232520     0.181341     3.527284     0.211983     1.424713   
std       0.043351     0.028652     1.306709     0.034413     0.472284   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.205530     0.164411     2.471432     0.190489     1.202789   
50%       0.231082     0.182270     3.325505     0.210560     1.355423   
75%       0.257225     0.197226     4.480652     0.234558     1.560931   
max       0.539050     0.317066     7.464070     0.306247     6.113347   

          ...             SHH_N        BAD_N       BCL2_N        pS6_N  \
count     ...       1080.000000  1080.000000  1080.000000  1080.000000   
mean      ...          0.226676     0.126770     0.099200     0.121521   
std       ...          0.028989     0.068206     0.063907     0.014276   
min       ...          0.155869     0.000000     0.000000     0.067254   
25%       ...          0.206395     0.121498     0.000000     0.110839   
50%       ...          0.224000     0.145587     0.119377     0.121626   
75%       ...          0.241655     0.167584     0.139331     0.131955   
max       ...          0.358289     0.282016     0.261506     0.158748   

           pCFOS_N        SYP_N    H3AcK18_N       EGR1_N     H3MeK4_N  \
count  1080.000000  1080.000000  1080.000000  1080.000000  1080.000000   
mean      0.121952     0.446073     0.141341     0.147525     0.154080   
std       0.040506     0.066432     0.083302     0.081074     0.101151   
min       0.000000     0.258626     0.000000     0.000000     0.000000   
25%       0.110337     0.398082     0.110493     0.136712     0.076340   
50%       0.124534     0.448459     0.144696     0.164866     0.174236   
75%       0.142427     0.490773     0.187174     0.196133     0.219242   
max       0.256529     0.759588     0.479763     0.360692     0.413903   

            CaNA_N  
count  1080.000000  
mean      1.337784  
std       0.317126  
min       0.586479  
25%       1.081423  
50%       1.317441  
75%       1.585824  
max       2.129791  

[8 rows x 77 columns]

In [16]:
standardize = lambda x: (x-x.mean()) / x.std()
standardizedData = new_data.pipe(standardize)
standardizedData.head()

DYRK1A_N   ITSN1_N    BDNF_N     NR1_N    NR2A_N    pAKT_N   pBRAF_N  \
0  0.316038  0.520184  2.149277  1.430549  2.262007 -0.315800 -0.131783   
1  0.359927  0.290769  1.796002  1.357544  1.942024 -0.481743 -0.297513   
2  0.338193  0.453303  1.921504  1.078990  1.875975 -0.542300 -0.196117   
3  0.069911  0.006663  0.775926  0.479334  1.202107 -0.222243 -0.170276   
4  0.041248  0.008059  0.779302  0.203912  0.928571 -0.447838 -0.269245   

   pCAMKII_N   pCREB_N    pELK_N    ...        SHH_N     BAD_N    BCL2_N  \
0  -0.882782  0.588160  0.690733    ...    -1.304799 -0.060376 -1.552238   
1  -0.945225  0.435553  0.363475    ...    -0.906305 -0.147904 -1.552238   
2  -0.951970  0.530712  0.289239    ...    -1.138084 -0.121131 -1.552238   
3  -1.052249 -0.144691  0.360742    ...    -1.192335  0.088133 -1.552238   
4  -1.066243 -0.576107  0.168366    ...    -0.726905  0.046683 -1.552238   

      pS6_N   pCFOS_N     SYP_N  H3AcK18_N    EGR1_N  H3MeK4_N    CaNA_N  
0 -1.065782 -0.336153 -0.285612  -0.318815 -0.194082 -0.255995  1.065407  
1 -1.045682 -0.435408 -0.067614  -0.352545 -0.153219 -0.226998  1.279698  
2 -0.925842 -0.388406 -0.154987  -0.353633 -0.174694 -0.263454  1.856178  
3 -1.284424 -0.263915 -0.818610  -0.131279 -0.000998 -0.070969  1.143960  
4 -1.172352 -0.277938 -0.179419  -0.274420 -0.088940 -0.056349  1.582797  

[5 rows x 77 columns]

In [24]:
#4. Select top 5 numerical features that separate the groups in the "class" column.

from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_selection import SelectKBest
numFeatures = 5
targetData =data['class']
numericalData = standardizedData
best_features = SelectKBest(mutual_info_classif, k=numFeatures).fit_transform(numericalData,targetData)
best=print(best_features)


[[ 0.31603774  0.41476379 -0.60937117 -0.45554769  1.06540732]
 [ 0.35992659  0.43528251 -0.70605887 -0.46182468  1.27969832]
 [ 0.33819257  0.38425192 -0.70102787 -0.3150436   1.85617837]
 ...
 [-0.78364088 -0.83619114  0.42850884  1.59339621  0.29338877]
 [-0.81346679 -0.90669536  0.55848046  1.64771336  0.20889942]
 [-0.48796274 -0.77520959  0.87241679  1.63944974  0.10473973]]


In [34]:
# 5. Show the scatter matrix for the selected features (with hue = class column) .
import seaborn as sns; sns.set(style="ticks", color_codes=True)
import pandas as pd  
#am convertit best_features in DataFrame
df=pd.DataFrame(best_features)
df.head(5)

0         1         2         3         4
0  0.316038  0.414764 -0.609371 -0.455548  1.065407
1  0.359927  0.435283 -0.706059 -0.461825  1.279698
2  0.338193  0.384252 -0.701028 -0.315044  1.856178
3  0.069911  0.112388 -0.698141 -0.162880  1.143960
4  0.041248  0.018994 -0.752764 -0.105095  1.582797

In [36]:
p=pd.DataFrame(new_data.loc[:, new_data.columns == 'class'])
#print(p)
df['class']=p
#print(df)
g = sns.pairplot(df, hue="class")

ValueError: Wrong number of items passed 0, placement implies 1

In [38]:
#6.Perform PCA on all standarized numerical features
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

no_components = nd.shape[1]
standardizedFeatures= StandardScaler().fit_transform(numericalData)
pca = PCA(n_components = no_components).fit(standardizedFeatures)

pcaFeatures = pd.DataFrame(pca.transform(standardizedFeatures))
pcaFeatures['class']=targetData
new_df=df.drop(['class'], axis=1)
print(new_df)
sns.pairplot(pcaFeatures,hue="class",vars=new_df)

NameError: name 'nd' is not defined

In [39]:
#7. Using a bar plot, show the variance explained by the first k principal components (with k = 1 to numberOfFeatures).
figure = plt.figure(figsize = (35,15))
x = np.arange(1,numberOfFeatures+1,1)
height = pca.explained_variance_ratio_.cumsum()
plt.xlabel('Principal component',fontdict = {'fontsize':20}) 
plt.ylabel('Explained variance',fontdict = {'fontsize':20})

plt.bar(x, height)
for i, v in enumerate(height):
    plt.text(x[i] - 0.25, v + 0.01, r'%.2f'%v)


NameError: name 'pca' is not defined